# Form implementation generated from reading ui file 'D:\qt designs\login.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from MainWindow import MainWindow


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 0, 781, 541))
        self.widget.setStyleSheet("background-color:black;")
        self.widget.setObjectName("widget")
        
        self.user_form = QtWidgets.QLineEdit(parent=self.widget)
        self.user_form.setGeometry(QtCore.QRect(250, 190, 261, 51))
        self.user_form.setText("")
        self.user_form.setObjectName("user_form")
        self.user_form.setStyleSheet("color:white; font-size:15pt; padding-left:5%;")
        self.password_form = QtWidgets.QLineEdit(parent=self.widget)
        self.password_form.setGeometry(QtCore.QRect(250, 310, 261, 51))
        self.password_form.setText("")
        self.password_form.setObjectName("password_form")
        self.password_form.setStyleSheet("color:white; font-size:15pt; padding-left:5%;")
        self.login_label = QtWidgets.QLabel(parent=self.widget)
        self.login_label.setGeometry(QtCore.QRect(330, 70, 111, 51))
        self.login_label.setStyleSheet("font-size:30pt;\n"
"font-weight:bold;\n"
"color:white;\n"
"background-color:rgba(255,255,255,0)")
        self.login_label.setObjectName("login_label")
        self.user_label = QtWidgets.QLabel(parent=self.widget)
        self.user_label.setGeometry(QtCore.QRect(250, 170, 91, 16))
        self.user_label.setStyleSheet("color:white;\n"
"font-size:10pt;\n"
"background-color:rgba(255,255,255,0)")
        self.user_label.setObjectName("user_label")
        self.password_label = QtWidgets.QLabel(parent=self.widget)
        self.password_label.setGeometry(QtCore.QRect(250, 290, 81, 16))
        self.password_label.setStyleSheet("color:white;\n"
"font-size:10pt;\n"
"background-color:rgba(255,255,255,0)")
        self.password_label.setObjectName("password_label")
        self.submit_PushButton = QtWidgets.QPushButton(parent=self.widget)
        self.submit_PushButton.setGeometry(QtCore.QRect(310, 420, 141, 41))
        self.submit_PushButton.setStyleSheet("color:white;\n"
"background-color:rgba(255,0,0,255);\n"
"font-size:15pt;\n"
"font-weight:bold;\n"
"padding-left:2%;\n"
"padding-right:2%;\n"
"padding-top:5%;\n"
"padding-bottom:5%;\n"
"border-radius:10;")
        
        self.submit_PushButton.setObjectName("submit_PushButton")
        self.error_label=QtWidgets.QLabel(parent=self.widget)
        self.error_label.setGeometry(QtCore.QRect(250, 470, 261, 21))
        self.error_label.setStyleSheet("color:red; background-color:rgba(255,255,255,0);font-size:15pt;")
        
        LoginWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=LoginWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        LoginWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "LoginWindow"))
        self.login_label.setText(_translate("LoginWindow", "Login"))
        self.user_label.setText(_translate("LoginWindow", "Username"))
        self.password_label.setText(_translate("LoginWindow", "Password"))
        self.submit_PushButton.setText(_translate("LoginWindow", "Submit"))

    
    def On_submit_clicked(self):
        username=self.user_form.text()
        password=self.password_form.text()
        with open("DS_users.txt" , "r") as file:
                for line in file:
                        stored_user,stored_password=line.strip().split(" ")
                        if username==stored_user and password==stored_password:
                                self.error_label.setText("")
                                self.Open_new_window()
                                return
                self.error_label.setText("Invalid username or password")
                
    def Open_new_window(self):
            
            self.ui=MainWindow()
            self.ui.show()
            LoginPage.hide()
        

        

# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     LoginPage = QtWidgets.QMainWindow()
#     ui = Ui_LoginWindow()
#     ui.setupUi(LoginPage)
#     ui.submit_PushButton.clicked.connect(ui.On_submit_clicked)
    
#     LoginPage.show()
    
#     sys.exit(app.exec())
